backend:
  name: github
  repo: zhutou369/hk-deepseek
  branch: main
  base_url: https://shrill-king-461b.zhutou757.workers.dev
  auth_endpoint: /auth

media_folder: "src/static/assets/img"
public_folder: "/static/assets/img"

display_type: list
show_preview_links: false

collections:
  - name: "posts"
    label: "文章發布"
    folder: "src/posts"
    create: true
    slug: "{{year}}{{month}}{{day}}-{{hour}}{{minute}}{{second}}-{{slug}}"
    fields:
      - {label: "文章標題", name: "title", widget: "string"}
      - {label: "SEO 頁面描述", name: "description", widget: "string"}
      - {label: "發布日期", name: "date", widget: "datetime", format: "YYYY-MM-DD HH:mm:ss"}
      - {label: "正文內容", name: "body", widget: "markdown"}
      - {label: "標籤", name: "tags", widget: "hidden", default: ["posts"]}
      - {label: "布局", name: "layout", widget: "hidden", default: "layouts/post.njk"}
