const SPAM_TITLE_PATTERN =
  /官方|權威|站群|SEOer|友鏈|友链|跨境流量|免翻牆|爆款文案|搞掂友鏈|全攻略|爽歪歪|自動檢測\+對接|狂降\d+%|技術白皮書|完整指南|SEO 霸屏|友鏈機器人/;
const SPAM_DESC_PATTERN = /專業技術解析與香港本地化實操指南|實戰帖|小夥伴們注意|手把手教你/;
const FORBIDDEN_PHRASES = [
  "綜上所述",
  "综上所述",
  "毋庸置疑",
  "在當今數字化時代",
  "在当今数字化时代",
  "業界領先",
  "业界领先",
  "全方位",
  "深度融合",
  "極致",
  "极致",
  "SEO 霸屏",
  "友鏈機器人"
];

function hasSpamSignals({ title = "", description = "", tags = [] } = {}) {
  const titleText = String(title);
  const descText = String(description);
  const tagList = Array.isArray(tags) ? tags : [];

  if (descText.includes("專業技術解析與香港本地化實操指南")) return true;
  if (SPAM_TITLE_PATTERN.test(titleText)) return true;
  if (SPAM_DESC_PATTERN.test(descText)) return true;
  if (tagList.includes("SEO優化")) return true;

  return false;
}

function isAutoGeneratedPost(inputPath = "") {
  return /\/\d{4}-\d{2}-\d{2}-post-/.test(String(inputPath));
}

function isPostIndexable(data, inputPath = "") {
  if (!data || data.noindex === true) return false;

  if (isAutoGeneratedPost(inputPath)) {
    return data.generated === true && data.featured === true && !hasSpamSignals(data);
  }

  if (data.generated === true && data.featured !== true) return false;

  return !hasSpamSignals(data);
}

function countOperationSteps(body = "") {
  const text = String(body);
  const explicitSteps =
    text.match(/(?:^|\n)\s*(?:#{1,3}\s*)?(?:第[一二三四五六七八九十\d]+步|步骤\s*\d+|步驟\s*\d+|\d+[.、)])/g) || [];
  const orderedListItems = text.match(/(?:^|\n)\s*\d+[.、)]/g) || [];

  return Math.max(explicitSteps.length, orderedListItems.length);
}

function passesFeaturedQuality(article) {
  if (!article || typeof article !== "object") return false;
  if (hasSpamSignals(article)) return false;

  const title = String(article.title || "");
  const description = String(article.description || "");
  const body = String(article.body || "");
  const fullText = `${title}\n${description}\n${body}`;

  for (const phrase of FORBIDDEN_PHRASES) {
    if (fullText.includes(phrase)) return false;
  }

  if (!/(?:v\d[\d.]*|版本|20\d{2}[-年/月]|DeepSeek API v)/i.test(body)) return false;
  if (countOperationSteps(body) < 3) return false;
  if (!/常見問題|FAQ|答疑|##\s*Q\d/i.test(body)) return false;
  if (!/我(?:測試|個人|建議|上週|試|用|們|最近|跑)|我個人/i.test(body)) return false;

  const bodyLength = body.replace(/\s/g, "").length;
  if (bodyLength < 500 || bodyLength > 4000) return false;

  const internalLinks = (body.match(/]\(\/posts\/[^)]+\)/g) || []).length;
  if (internalLinks < 1) return false;

  return true;
}

module.exports = {
  hasSpamSignals,
  isPostIndexable,
  passesFeaturedQuality
};
